version: "3.8"

services:
  mcp-server:
    build: .
    container_name: iexec-mcp-server
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${PRIVATE_KEY}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: node build/index.js
