version: "3.8"

services:
  mcp-server:
    image: iexechub/mcp-server:latest
    build: .
    container_name: iexec-mcp-server
    environment:
      - REMOTE=${REMOTE}
      - PORT=${PORT}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
    volumes:
      - ${PRIVATE_KEY_PATH}:/root/.ethereum/keystore:ro
    ports:
      - "3000:3000" # expose only if REMOTE=true
    stdin_open: true # required for stdio
    tty: true
    restart: unless-stopped
