name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  publish:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@docker-build-v1.1.1
    with:
      dockerfile: "Dockerfile"
      image-name: "iexechub/mcp-server"
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-pat: ${{ secrets.DOCKERHUB_TOKEN }}
